modules/control_university/controllers/MainController.php
<?php

namespace app\modules\control_university\controllers;
use app\modules\control_university\models\Xodimlar;
use app\modules\control_university\models\XodimlarSearch;
use app\modules\control_university\models\Bolimlar;
use app\modules\control_university\models\Lavozimlar;
use app\modules\control_university\models\Qaydnoma;
use yii\db\Query;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use Yii;
/**
 * Default controller for the `control_university` module
 */
class MainController extends Controller {

    public $layout = 'main';

    public function actionIndex(){

        $searchModel = new XodimlarSearch();         
        $dataProvider  = new ActiveDataProvider([
	    'query' => Xodimlar::find()->select(['xodimID','ismi','tabel_nomer','cardNo','uy_manzil','tel_raqam']),
         'pagination' => [
            'pageSize' => 15,
	    ],         
	   ]);
        return $this->render('index',[
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
	   ]);
    }
    public function actionLogout(){

	   if( !Yii::$app->user->isGuest ){
	       Yii::$app->user->logout();
            return $this->goHome();   
	   }
        return $this->goHome();
    }
    public function actionHisobot(){
         
	 $query = new Query();
      $query->select([
          'id'=>'xd.id',
          'xodimID'=>'xd.xodimID',   
          'tabel_nomer'=>'xd.tabel_nomer',
          'ismi' => 'xd.ismi',
          'bolim' => 'b.nomlanishi',
          'lavozim' => 'l.nomlanishi',
          'qaydlov_vaqti' => 'q.authDateTime', 
          'karta_nomer' => 'q.cardNo'  
		])->from([
          'xd' => Xodimlar::tableName() 
		])->innerJoin(['q' => Qaydnoma::tableName()], 'q.employeeID=xd.xodimID OR q.cardNo=xd.cardNo' 
      	  )->innerJoin(['b'=> Bolimlar::tableName()], 'b.id=xd.bolimlar_id'
		  )->innerJoin(['l'=> Lavozimlar::tableName()], 'l.id=xd.lavozimlar_id'
		  )->all();
  
        $searchModel = new XodimlarSearch();       
        $dataProvider  = new ActiveDataProvider([
	    'query' => $query,
         'pagination' => [
            'pageSize' => 15,
	    ],         
	   ]);

        return $this->render('hisobot', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
       
    }    
    
}

modules/control_university/views/layouts/begin-tabcontent.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>

               <div class="tab-content">            
                    <div class="tab-pane fade show active" id="admin-Dashboard" role="tabpanel">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h3 class="card-title"><?=$this->title?></h3>
                                        <div class="card-options">
                                            <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
                                            <a href="#" class="card-options-fullscreen" data-toggle="card-fullscreen"><i class="fe fe-maximize"></i></a>
                                            <a href="#" class="card-options-remove" data-toggle="card-remove"><i class="fe fe-x"></i></a>
                                        </div>
                                    </div>
  
                                  <div class="card-body">
                                        <div class="table-responsive">

modules/control_university/views/layouts/body-menu.php
<?php

use yii\helpers\Url;

?>
              <div class="row clearfix row-deck">
                    <div class="col-6 col-md-4 col-xl-2">
                        <div class="card">
                            <div class="card-body ribbon">                                
                                <a href="<?= Url::to(['xodimlar/']) ?>" class="my_sort_cut text-muted">
                                    <i class="fa fa-users"></i><span>Xodimlar</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-6 col-md-4 col-xl-2">
                        <div class="card">
                            <div class="card-body">
                                <a href="<?= Url::to(['main/hisobot']) ?>" class="my_sort_cut text-muted">
                                    <i class="fa fa-clock-o"></i><span>Ish vaqtini hisobga olish hisoboti</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-6 col-md-4 col-xl-2">
                        <div class="card">
                            <div class="card-body">
                                <a href="<?= Url::to(['ishjadvallari/']) ?>" class="my_sort_cut text-muted">
                                    <i class="fa fa-calendar-o"></i><span>Ish grafigi</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-6 col-md-4 col-xl-2">
                        <div class="card">
                            <div class="card-body ribbon">                                
                                <a href="<?= Url::to(['bolimlar/']) ?>" class="my_sort_cut text-muted">
                                    <i class="fa fa-sitemap"></i><span>Bo'limlar</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-6 col-md-4 col-xl-2">
                        <div class="card">
                            <div class="card-body">
                                <a href="<?= Url::to(['lavozimlar/']) ?>" class="my_sort_cut text-muted">
                                    <i class="fa fa-black-tie"></i><span>Lavozimlar</span>
                                </a>
                            </div>
                        </div>
                    </div>                    
                    <div class="col-6 col-md-4 col-xl-2">
                        <div class="card">
                            <div class="card-body">
                                <a href="<?= Url::to(['qaydnoma/']) ?>" class="my_sort_cut text-muted">
                                    <i class="fa fa-bullhorn"></i>
                                    <span>Qaydnoma</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

modules/control_university/views/layouts/end-tabcontent.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>

                                       </div>  
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>                  
                </div>

modules/control_university/views/layouts/header-top.php
<?php

use yii\helpers\Url;


?>
    <!-- Start Main top header -->
    <div id="header_top" class="header_top">
        <div class="container">
            <div class="hleft">
                <a class="header-brand" href="<?= Url::to(\Yii::$app->getHomeUrl())?>"><i class="fa fa-graduation-cap brand-logo"></i></a>
                <div class="dropdown">
                    <a href="javascript:void(0)" class="nav-link icon menu_toggle"><i class="fe fe-align-center"></i></a>                    
                </div>
            </div>
            <div class="hright">
                <a href="javascript:void(0)" class="nav-link icon settingbar"><i class="fe fe-settings"></i></a>
                <a href="<?= Url::to(['main/logout']) ?>" class="nav-link icon settingbar"><i class="fe fe-power"></i></a>                
            </div>
        </div>
    </div>

modules/control_university/views/layouts/left-sidebar.php
<?php
use app\modules\control_university\assets\MainControlUniversityAssets as MainAsset;
use yii\helpers\Url;

MainAsset::register($this);
?>

    <!-- Start Main leftbar navigation -->
      <div id="left-sidebar" class="sidebar">
        <h5 class="brand-name">Control university<a href="javascript:void(0)" class="menu_option float-right"><i class="icon-grid font-16" data-toggle="tooltip" data-placement="left" title="" data-original-title="Grid &amp; List Toggle"></i></a></h5>
        <ul class="nav nav-tabs">
            <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#menu-uni">University</a></li>
            <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#menu-admin">Admin</a></li>
        </ul>
        <div class="tab-content mt-3">
            <div class="tab-pane fade active show" id="menu-uni" role="tabpanel">
                <nav class="sidebar-nav">
                    <ul class="metismenu">
                        <li><a href="<?= Url::to(['xodimlar/']) ?>"><i class="fa fa-users"></i><span>Xodimlar</span></a></li>
                        <li><a href="<?= Url::to(['main/hisobot']) ?>"><i class="fa fa-clock-o"></i><span>Ish vaqtini hisobga olish hisoboti</span></a></li>                        
                        <li><a href="<?= Url::to(['ishjadvallari/']) ?>"><i class="fa fa-calendar-o"></i><span>Ish grafigi</span></a></li>
                        <li><a href="<?= Url::to(['bolimlar/']) ?>"><i class="fa fa-sitemap"></i><span>Bo'limlar</span></a></li>
                        <li><a href="<?= Url::to(['lavozimlar/']) ?>"><i class="fa fa-black-tie"></i><span>Lavozimlar</span></a></li>
                        <li><a href="<?= Url::to(['qaydnoma/']) ?>"><i class="fa fa-bullhorn"></i><span>Qaydnoma</span></a></li>
                        <li class="g_heading">Extra</li>
                        <li><a href="events.html"><i class="fa fa-calendar"></i><span>Calender</span></a></li>
                    </ul>
                </nav>
            </div>
            <div class="tab-pane fade" id="menu-admin" role="tabpanel">
                <nav class="sidebar-nav">
                    <ul class="metismenu">
                        <li><a href=""><i class="fa fa-minus"></i><span>Foydalanuvchilar</span></a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>

modules/control_university/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\modules\control_university\assets\MainControlUniversityAssets as MainAsset;
use yii\helpers\Html;

MainAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" dir="ltr">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags(); ?>
    <title><?= Html::encode($this->title) ?></title>

    <?php $this->head() ?>
</head>
<body class="sidebar-white font-opensans">
<?php $this->beginBody() ?>

<!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
    </div>
</div>
<div id="main_content">

<?php $this->beginContent('@mcu/views/layouts/header-top.php'); ?>
<?php $this->endContent(); ?>

<?php $this->beginContent('@mcu/views/layouts/left-sidebar.php'); ?>
<?php $this->endContent(); ?>

<?php $this->beginContent('@mcu/views/layouts/right-sidebar.php'); ?>
<?php $this->endContent(); ?>

<?php $this->beginContent('@mcu/views/layouts/page-begin.php'); ?>
<?php $this->endContent(); ?>
 
<?= Html::tag('div', Html::tag('div', $content ,['class'=>'container-fluid'] ), ['class'=>'section-body mt-4'])  ?>

<?php $this->beginContent('@mcu/views/layouts/page-end.php'); ?>
<?php $this->endContent(); ?>

</div>

<?php $this->endBody() ?>
</body>
</html>

<?php $this->endPage() ?>

modules/control_university/views/layouts/page-begin.php
<?php

use app\modules\control_university\assets\MainControlUniversityAssets as MainAsset;
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

$bundle = MainAsset::register($this);

?>

    <!-- Start project content area -->
    <div class="page">
        <!-- Start Page header -->
        <div class="section-body" id="page_top">
            <div class="container-fluid">
                <div class="page-header">
                    <div class="left">                        
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Siz nimani topmoqchisiz?">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="button">Search</button>
                            </div>
                        </div>
                    </div>
                    <div class="right">                       
                        <div class="notification d-flex">                                            
                            
                            <div class="dropdown d-flex">
                                <a href="javascript:void(0)" class="chip ml-3" data-toggle="dropdown">
                                    <span class="avatar" style="background-image: url(<?=$bundle->baseUrl?>/images/xs/avatar.jpg)"></span>Name</a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                    <a class="dropdown-item" href=""><i class="dropdown-icon fe fe-user"></i> Profil</a>
                                    <a class="dropdown-item" href=""><i class="dropdown-icon fe fe-settings"></i> Sozlamalar</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="javascript:void(0)"><i class="dropdown-icon fe fe-help-circle"></i> Yordam kerakmi?</a>
                                    <a class="dropdown-item" href="<?= Url::to(['main/logout']) ?>"><i class="dropdown-icon fe fe-log-out"></i> Chiqish</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Start Page title and tab bredcumbs -->
        <div class="section-body">
            <div class="container-fluid">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="header-action">
                        <h1 class="page-title"></h1>

                        <?=Breadcrumbs::widget([
                        'homeLink' => ['label'=>'Bosh menu', 'url'=>Url::to(['main/index']) ],
                        'links' => isset(Yii::$app->params['breadcrumbs']) ? Yii::$app->params['breadcrumbs'] : [],
                        'tag' => 'ol',
                        'itemTemplate' => "<li class=\"breadcrumb-item\">{link}</li>\n",
                        'activeItemTemplate' => "<li class=\"breadcrumb-item active\" aria-current=\"page\">{link}</li>\n",
                        'options' => ['class'=>'breadcrumb page-breadcrumb']                              
                        ]) 
                        ?>                      

                    </div>
                    
                </div>
            </div>
        </div>
    

modules/control_university/views/layouts/page-end.php
<?php 

?>
      
        <!-- Start main footer -->
        <div class="section-body">
            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">                        
                        <div class="col-md-12 col-sm-12 text-md-right">
                            <ul class="list-inline mb-0">
                                <li class="list-inline-item">Author: Oybek N.E. © 2021 <a href="http://sf.tdpu.uz/">Nizomiy nomidagi TDPU</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

modules/control_university/views/layouts/right-sidebar.php
<?php
use app\modules\control_university\assets\MainControlUniversityAssets as MainAsset;
$bundle = MainAsset::register($this);
?>
    <!-- Start Rightbar setting panel -->
    <div id="rightsidebar" class="right_sidebar">
        <a href="javascript:void(0)" class="p-3 settingbar float-right"><i class="fa fa-close"></i></a>
        <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#Settings" aria-expanded="true">Settings</a></li>
        </ul>
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane vivify fadeIn active" id="Settings" aria-expanded="true">
                <div class="mb-4">
                    <h6 class="font-14 font-weight-bold text-muted">Theme Color</h6>
                    <ul class="choose-skin list-unstyled mb-0">
                        <li data-theme="azure"><div class="azure"></div></li>
                        <li data-theme="indigo"><div class="indigo"></div></li>
                        <li data-theme="purple"><div class="purple"></div></li>
                        <li data-theme="orange"><div class="orange"></div></li>
                        <li data-theme="green"><div class="green"></div></li>
                        <li data-theme="cyan" class="active"><div class="cyan"></div></li>
                        <li data-theme="blush"><div class="blush"></div></li>
                        <li data-theme="white"><div class="bg-white"></div></li>
                    </ul>
                </div>
                <div class="mb-4">
                    <h6 class="font-14 font-weight-bold text-muted">Font Style</h6>
                    <div class="custom-controls-stacked font_setting">
                        <label class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" name="font" value="font-muli" checked="">
                            <span class="custom-control-label">Muli Google Font</span>
                        </label>
                        <label class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" name="font" value="font-montserrat">
                            <span class="custom-control-label">Montserrat Google Font</span>
                        </label>
                        <label class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" name="font" value="font-poppins">
                            <span class="custom-control-label">Poppins Google Font</span>
                        </label>
                    </div>
                </div>
                <div>
                    <h6 class="font-14 font-weight-bold mt-4 text-muted">General Settings</h6>
                    <ul class="setting-list list-unstyled mt-1 setting_switch">
                        <li>
                            <label class="custom-switch">
                                <span class="custom-switch-description">Night Mode</span>
                                <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input btn-darkmode">
                                <span class="custom-switch-indicator"></span>
                            </label>
                        </li>
                        <li>
                            <label class="custom-switch">
                                <span class="custom-switch-description">Fix Navbar top</span>
                                <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input btn-fixnavbar">
                                <span class="custom-switch-indicator"></span>
                            </label>
                        </li>
                        <li>
                            <label class="custom-switch">
                                <span class="custom-switch-description">Header Dark</span>
                                <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input btn-pageheader">
                                <span class="custom-switch-indicator"></span>
                            </label>
                        </li>
                        <li>
                            <label class="custom-switch">
                                <span class="custom-switch-description">Min Sidebar Dark</span>
                                <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input btn-min_sidebar">
                                <span class="custom-switch-indicator"></span>
                            </label>
                        </li>
                        <li>
                            <label class="custom-switch">
                                <span class="custom-switch-description">Sidebar Dark</span>
                                <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input btn-sidebar">
                                <span class="custom-switch-indicator"></span>
                            </label>
                        </li>
                        <li>
                            <label class="custom-switch">
                                <span class="custom-switch-description">Icon Color</span>
                                <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input btn-iconcolor">
                                <span class="custom-switch-indicator"></span>
                            </label>
                        </li>
                        <li>
                            <label class="custom-switch">
                                <span class="custom-switch-description">Gradient Color</span>
                                <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input btn-gradient" checked="">
                                <span class="custom-switch-indicator"></span>
                            </label>
                        </li>
                        <li>
                            <label class="custom-switch">
                                <span class="custom-switch-description">Box Shadow</span>
                                <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input btn-boxshadow">
                                <span class="custom-switch-indicator"></span>
                            </label>
                        </li>
                        <li>
                            <label class="custom-switch">
                                <span class="custom-switch-description">RTL Support</span>
                                <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input btn-rtl">
                                <span class="custom-switch-indicator"></span>
                            </label>
                        </li>
                        <li>
                            <label class="custom-switch">
                                <span class="custom-switch-description">Box Layout</span>
                                <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input btn-boxlayout">
                                <span class="custom-switch-indicator"></span>
                            </label>
                        </li>
                    </ul>
                </div>
                <hr>
                <div class="form-group">
                    <label class="d-block">Storage <span class="float-right">77%</span></label>
                    <div class="progress progress-sm">
                        <div class="progress-bar" role="progressbar" aria-valuenow="77" aria-valuemin="0" aria-valuemax="100" style="width: 77%;"></div>
                    </div>
                    <button type="button" class="btn btn-primary btn-block mt-3">Upgrade Storage</button>
                </div>
            </div>            
        </div>
    </div>