modules/control_university/models/Qaydnoma.php
<?php

namespace app\modules\control_university\models;

use Yii;

/**
 * This is the model class for table "{{%attlog}}".
 *
 * @property string $employeeID
 * @property string $authDateTime
 * @property string $authDate
 * @property string $authTime
 * @property string $direction
 * @property string $divaceName
 * @property string $divaceSN
 * @property string $personName
 * @property string $cardNo
 */
class Qaydnoma extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%attlog}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['employeeID', 'authDateTime', 'authDate', 'authTime', 'direction', 'divaceName', 'divaceSN', 'personName', 'cardNo'], 'required'],
            [['authDateTime', 'authDate', 'authTime'], 'safe'],
            [['employeeID', 'direction', 'divaceName', 'divaceSN', 'personName'], 'string', 'max' => 50],
            [['cardNo'], 'string', 'max' => 64],
            
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'employeeID' => 'Employee ID',
            'authDateTime' => 'Auth Date Time',
            'authDate' => 'Auth Date',
            'authTime' => 'Auth Time',
            'direction' => 'Direction',
            'divaceName' => 'Divace Name',
            'divaceSN' => 'Divace Sn',
            'personName' => 'Person Name',
            'cardNo' => 'Card No',
        ];
    }
}

modules/control_university/controllers/QaydnomaController.php
<?php

namespace app\modules\control_university\controllers;

use Yii;
use app\modules\control_university\models\Qaydnoma;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
/**
 * XodimlarController implements the CRUD actions for Xodimlar model.
 */
class QaydnomaController extends Controller
{
    public $layout = 'main';
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Xodimlar models.
     * @return mixed
     */
    public function actionIndex()
    {                
        $dataProvider  = new ActiveDataProvider([
	    'query' => Qaydnoma::find(),
         'pagination' => [
            'pageSize' => 15,
	    ],         
	   ]);

        return $this->render('index', [            
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Xodimlar model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Xodimlar model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Qaydnoma();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->employeeID]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Xodimlar model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->employeeID]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Xodimlar model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Xodimlar model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Xodimlar the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Qaydnoma::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/control_university/views/qaydnoma/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>
<?php $this->beginContent('@mcu/views/layouts/begin-tabcontent.php'); ?>
<?php $this->endContent(); ?>

<div class="qaydnoma-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'employeeID')->textInput(['maxlength' => 50]) ?>
    <?= $form->field($model, 'authDateTime')->input('datetime') ?>
    <?= $form->field($model, 'authDate')->input('date') ?>
    <?= $form->field($model, 'authTime')->input('time') ?>
    <?= $form->field($model, 'direction')->textInput(['maxlength' => 50]) ?>
    <?= $form->field($model, 'divaceName')->textInput(['maxlength' => 50]) ?>
    <?= $form->field($model, 'divaceSN')->textInput(['maxlength' => 50]) ?>
    <?= $form->field($model, 'personName')->textInput(['maxlength' => 50]) ?>
    <?= $form->field($model, 'cardNo')->textInput(['maxlength' => 64]) ?>


    <div class="form-group">
        <?= Html::submitButton('Saqlash', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php $this->beginContent('@mcu/views/layouts/end-tabcontent.php'); ?>
<?php $this->endContent(); ?>

modules/control_university/views/qaydnoma/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<div class="qaydnoma-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'employeeID') ?>
    <?= $form->field($model, 'authDateTime') ?>    
    <?= $form->field($model, 'direction') ?>    
    <?= $form->field($model, 'personName') ?>
    <?= $form->field($model, 'cardNo') ?>

    <div class="form-group">
        <?= Html::submitButton('Qidirish', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Qayta yuklash', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/control_university/views/qaydnoma/index.php
<?php

use yii\grid\GridView;
use yii\grid\ActionColumn;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Qaydnoma';
Yii::$app->params['breadcrumbs'][] = $this->title;

?>

<?php $this->beginContent('@mcu/views/layouts/begin-tabcontent.php'); ?>
<?php $this->endContent(); ?>

   <?= 
    GridView::widget([
      'dataProvider' => $dataProvider,      
      'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        'employeeID',
        'authDateTime',        
        'authDate', 
        'authTime', 
        'direction',                                                  
        'personName',                                           
        'cardNo',                                           
        [
          'class' => 'yii\grid\ActionColumn',
          'template' => '{view} {update} {delete}',          
          'buttons'=>[
		  'view' => function($url, $model, $key){
		     return Html::a('', ['qaydnoma/view', 'id'=>$model->employeeID]);
	     	},
		  'update' => function($url, $model, $key){
		     return Html::a('', ['qaydnoma/update', 'id'=>$model->employeeID]);
	     	},
		  'delete' => function($url, $model, $key){
		     return Html::a('', ['qaydnoma/delete', 'id'=>$model->employeeID]);
	     	}
		],
	   ], 
	],  
    ])
  ?>
                                                                                                                  
<?php $this->beginContent('@mcu/views/layouts/end-tabcontent.php'); ?>
<?php $this->endContent(); ?>

modules/control_university/views/qaydnoma/update.php
<?php

use yii\helpers\Html;

$this->title = $model->employeeID . ' ma\'lumotini o\'zgartirish.';
\Yii::$app->params['breadcrumbs'][] = ['label' => 'Xodimlar', 'url' => ['index']];
\Yii::$app->params['breadcrumbs'][] = ['label' => $model->employeeID, 'url' => ['view', 'id' => $model->id]];
\Yii::$app->params['breadcrumbs'][] = 'O\'zgartirish';
?>

<div class="qaydnoma-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/control_university/views/qaydnoma/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\web\YiiAsset;


$this->title = $model->employeeID;
\Yii::$app->params['breadcrumbs'][] = ['label' => 'Qaydnoma', 'url' => ['index']];
\Yii::$app->params['breadcrumbs'][] = $this->title;

YiiAsset::register($this);
?>

<?php $this->beginContent('@mcu/views/layouts/begin-tabcontent.php'); ?>
<?php $this->endContent(); ?>

<div class="qaydnoma-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('O\'zgartirish', ['update', 'id' => $model->employeeID], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->employeeID], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Siz bu ma\'lumotni o\'chirmoqchimisiz?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'xodimID',
            'ismi',        
            'tabel_nomer', 
            'cardNo', 
            'uy_manzil', 
            'tel_raqam',                                           
        ],
    ]) ?>

</div>
<?php $this->beginContent('@mcu/views/layouts/end-tabcontent.php'); ?>
<?php $this->endContent(); ?>